openapi: 3.1.0
info:
  title: API
  version: 1.0.0
servers:
  - url: http://localhost:14000
    description: CMS MyDNA
paths:
  /api/categories:
    get:
      tags:
        - Categories
      summary: Get all categories
      responses:
        '200':
          description: A list of categories
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
    post:
      tags:
        - Categories
      summary: Create a new category
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
      responses:
        '201':
          description: Category created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        422:
          description: Unprocessable entity/content
  /api/categories/{id}:
    get:
      tags:
        - Categories
      summary: Get a category by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the category
      responses:
        '200':
          description: A category
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          description: Category not found
    patch:
      tags:
        - Categories
      summary: Update a category by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the category
      responses:
        '200':
          description: Category resource updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Category'
    delete:
      tags:
        - Categories
      summary: Delete a category by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the category
      responses:
        '204':
          description: Category resource deleted
        409:
          description: Conflict
  /api/comments:
    get:
      tags:
        - Comments
      summary: Get all comments
      responses:
        '200':
          description: A list of comments
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Comment'
    post:
      tags:
        - Comments
      summary: Create a new comment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
      responses:
        '201':
          description: Comment created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        422:
          description: Unprocessable entity/content
  /api/comments/{id}:
    get:
      tags:
        - Comments
      summary: Get a comment by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the comment
      responses:
        '200':
          description: A comment
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '404':
          description: Comment not found
    patch:
      tags:
        - Comments
      summary: Update a comment by ID
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
          description: The ID of the comment
      responses:
        '200':
          description: Comment resource updated
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Comment'
        '404':
          description: Comment not found
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Comment'
    delete:
      tags:
        - Comments
      summary: Delete a comment by ID
      parameters:
          - name: id
            in: path
            required: true
            schema:
                type: integer
            description: The ID of the comment
      responses:
        '204':
          description: Comment resource deleted
components:
  schemas:
    Category:
      type: object
      description: A category
      deprecated: false
      properties:
        id:
          readOnly: true
          type: integer
          example: 1
        name:
          type: string
          example: "Rock"
    Comment:
      type: object
      description: A comment
      deprecated: false
      properties:
        id:
          readOnly: true
          type: integer
          example: 1
        content:
          type: string
          example: "This is a comment"
        post_id:
          type: integer
          example: 1
